### ISSUE TITLE
Margin Problem with Social Media Buttons

### ISSUE THREAD

**Issue by Gzxgzxgzx** [Gzxgzxgzx/Website#3]
```css
    .socialmedia-buttons img { padding: 0; margin: 0px 5px 10px 5px !important; }
```
see: http://s607012897.onlinehome.us/
